### ISSUE TITLE
Pylint Error displayed when have objects = models.Manager() in Model

### ISSUE THREAD

**Issue by yybot1** [PyCQA/pylint-django#144]
models.py
```
class ABC(models.Model):
    objects = models.Manager() # default manager
```

views.py
```
# E1136:Value 'ABC.objects.all()' is unsubscriptable
record = ABC.objects.all()[0]
```

Visual Studio Code 1.21.1
Windows 10
Python 3.6.4
pip list
astroid (1.6.2)
attrs (17.4.0)
colorama (0.3.9)
Django (2.0.3)
djangorestframework (3.7.7)
isort (4.3.4)
lazy-object-proxy (1.3.1)
mccabe (0.6.1)
more-itertools (4.1.0)
pip (9.0.3)
pluggy (0.6.0)
py (1.5.3)
pylint (1.8.3)
pylint-django (0.9.4)
pylint-plugin-utils (0.2.6)
pytest (3.5.0)
pytest-django (3.1.2)
pytz (2018.3)
rope (0.10.7)
selenium (3.11.0)
setuptools (28.8.0)
six (1.11.0)
wrapt (1.10.11)

**Comment by stugots** [comment]
I'm also seeing this.
