### ISSUE TITLE
Suppress protected-access warning about User._default_manager()

### ISSUE THREAD

**Issue by edmorley** [PyCQA/pylint-django#148]
Hi

For this method ([here](https://github.com/mozilla/treeherder/blob/0ea4717230c2172e9dbde2ca7897cd5ab276f919/treeherder/auth/backends.py#L151-L156)):

```python
from django.contrib.auth.models import User


class AuthBackend(object):

    # ...

    def get_user(self, user_id):
        try:
            return User._default_manager.get(pk=user_id)
        except User.DoesNotExist:
            return None
```

pylint warns about:
```
Access to a protected member _default_manager of a client class (W0212: protected-access)
```

This seems like something that pylint-django might be able to suppress? (Given that `._default_manager()` is an [official API](https://docs.djangoproject.com/en/1.11/topics/db/managers/#django.db.models.Model._default_manager))

The above was using:
Python 2.7.14
pylint==1.8.4
pylint-django==0.9.4
pylint-plugin-utils==0.2.6
astroid==1.6.3

**Comment by carlio** [comment]
Yes it could suppress it but I don't quite see the reason to - seems like pylint is quite rightly warning that you're accessing something that is not intended to be common usage. Django also moved `_meta` to `meta` for that reason once they decided it was no longer an internal thing.

I'm not sure how many people use this API, I could (and am often!) wrong, but simply disabling the error with a comment instruction using a comment on that line would avoid being a bit too heavy-handed with the plugin disabling more than necessary.

http://pylint-messages.wikidot.com/all-codes might help - see also https://pylint.readthedocs.io/en/latest/faq.html#message-control

**Comment by edmorley** [comment]
Hi! I was sure the Django docs referenced `_default_manager` specifically in their example auth backend, but I can't find it now.

**Comment by atodorov** [comment]
@edmorley the link you've posted in comment 0 states:

> You can specify a custom default manager using Meta.default_manager_name.

See:
https://docs.djangoproject.com/en/1.11/ref/models/options/#django.db.models.Options.default_manager_name

Either use this new Django API or disable pylint warnings where necessary in your code base. Closing.
