### ISSUE TITLE
Proposal: rule to suggest using fields instead of exclude in ModelForm

### ISSUE THREAD

**Issue by federicobond** [PyCQA/pylint-django#168]
Using `exclude` in ModelForm.Meta is an antipattern and can easily become a security issue if one is not careful. ModelForms should always define their fields explicitly.

I can contribute a patch if you are interested in this. Also, I'm not sure what to name this rule. `modelform-uses-exclude`?

**Comment by atodorov** [comment]
Please send a PR so I can review.

Can you post more info about Meta.exclude and why it could be a security issue? I'm just curious. 

As for the name, I don't have any particular preferences.

**Comment by federicobond** [comment]
Say you add a BooleanField to a model that controls whether users are allowed to execute a privileged action on a certain object, and default it to False. If you forget to explicitly exclude this field from a form visible to the user, it will now show up as another input ready to be modified and submitted.

If the form data is submitted via AJAX or if the form is rendered field by field, you may not even notice that the new field is now editable.

**Comment by atodorov** [comment]
implemented in #169.
