### ISSUE TITLE
Several issues after upgrading to python 3.7 to django 2.0.7

### ISSUE THREAD

**Issue by vaibhavhrt** [PyCQA/pylint-django#176]
**WARNING:**  Please do not report issues about missing Django, see
[README](https://github.com/PyCQA/pylint-django#installation)!

**TODO:** make sure to post the output of `pip freeze`
pip freeze
astroid==1.6.5
beautifulsoup4==4.6.0
bs4==0.0.1
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
colorama==0.3.9
Django==2.0.7
idna==2.7
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
mysqlclient==1.3.13
pycparser==2.18
pylint==1.9.2
pylint-django==0.11.1
pylint-plugin-utils==0.3
pytz==2018.5
requests==2.19.1
selenium==3.13.0
six==1.11.0
urllib3==1.23
wrapt==1.10.11

**NOTES:**  make sure you have the latest version of 3rd party packages
like `rest_framework`, `factory`, `model_utils`, etc. before reporting
issues!

After I upgraded to python 3.7 from 3.6 and django 2.0.7 from 2.0.5 I am encountering several problems.
1. In first line of models.py there is always F0002 error, no matter what the code is in that line. I disabled that error in rcfile

2. When i add this -> path('profile/', views.profile, name="profile"),
  in my urlpatterns, even if I have NOT yet defined the function profile still it doesn't generates any error.

3. There used to be several warning and info in all my files(which I was planning to fix later) but now there is just : 
    a. Warnings about line length greater than 100 char; and
    b. Warnings about missing module docstring (even this doesn't appears in some files where I have no docstring). 

It's been like only an hour since I upgraded my python as time passes I will figure out what else is wrong.

**Comment by atodorov** [comment]
Can you retry with pylint-django 2.0 that was released today ?

**Comment by vaibhavhrt** [comment]
@atodorov thanks for notifying about the new release, it's much better now. I am seeing a lot more info and warnings now as I used to. Looks like all the three issues I listed above are solved now.
But now there is another issue.

    from django.contrib.auth.models import User, AbstractUser
    
    class User(AbstractUser):
        pass

As you can see above I am extending Django auth's default User model but don't change anything. It's because so that I can later alter the User model if required easily without messing up my database migrations. But I am getting this error message `E0102:class already defined line 6` at the line `class User(AbstractUser):`

**Comment by carlio** [comment]
@vaibhavhrt I assume that's because you are importing User then trying to redefine it, as the error suggests. Change User to MyUser and see if you still get it. Either way I do not believe this is a pylint-django error so I'll close this as the original problems reported are fixed.

**Comment by vaibhavhrt** [comment]
@carlio yeah my bad, I should be importing just the AbstractUser model, not both models. Fixed it thanks.
