### ISSUE TITLE
Support for Python 2.7 and Django 1.11.16

### ISSUE THREAD

**Issue by py4on** [PyCQA/pylint-django#199]
Does this project still support Python 2.7? I'm working on a legacy Django codebase at the moment and `pylint` is driving me crazy but I can't seem to get `pylint-django` installed. The latest of your releases can't resolve dependencies as you no longer support `pylint <2.0`. I've tried some earlier releases but it chokes when attempting to install `astroid<2.0,>=1.6,>=2.0.0`. Could you point me to the last stable release that will work?

```
appnope==0.1.0
argh==0.26.2
astroid==1.6.5
atomicwrites==1.2.1
attrs==18.2.0
autopep8==1.4
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
colorama==0.3.9
configparser==3.5.0
coverage==4.5.1
decorator==4.3.0
Django==1.11.16
django-bootstrap3==11.0.0
django-crontab==0.7.1
django-debug-toolbar==1.10.1
django-impersonate==1.3
django-simple-history==2.4.0
docopt==0.6.2
easy-thumbnails==2.5
enum34==1.1.6
et-xmlfile==1.0.1
flake8==3.5.0
funcsigs==1.0.2
futures==3.2.0
geographiclib==1.49
geopy==1.17.0
ipython==5.8.0
ipython-genutils==0.2.0
isort==4.3.4
jdcal==1.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
mock==2.0.0
model-mommy==1.6.0
more-itertools==4.3.0
MySQL-python==1.2.5
openpyxl==2.5.8
pathlib2==2.3.2
pathtools==0.1.2
pbr==4.3.0
pdfcrowd==4.3.5
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.3.0
pluggy==0.7.1
pprint==0.1
prompt-toolkit==1.0.15
ptyprocess==0.6.0
py==1.6.0
pycodestyle==2.3.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.9.3
pytest==3.8.2
pytest-django==3.4.3
pytest-sugar==0.9.1
pytest-watch==4.2.0
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.13
scandir==1.9.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sqlparse==0.2.4
termcolor==1.1.0
traitlets==4.3.2
watchdog==0.9.0
wcwidth==0.1.7
wrapt==1.10.11
xlrd==1.1.0
xlutils==2.0.0
xlwt==1.3.0
```

**Comment by atodorov** [comment]
No it doesn't. We depend on the latest version of pylint which doesn't support 2.7 anymore.

**Comment by py4on** [comment]
Ok, understood - would you consider dropping a note to this effect in the Readme?

**Comment by carlio** [comment]
I think 0.8 was when python2 was properly dropped so 0.7.2 is the last release with the python 2 classifier in setup.py. Not sure if it will 100% work but worth a try, sorry it was almost a year ago so can't remember the exact timeline for removing Py2 support.

@atodorov might be worth adding a specific 'py2' tag to the last version that handled python 2.
