### ISSUE TITLE
It still show warning for Meta class

### ISSUE THREAD

**Issue by ArtemBernatskyy** [PyCQA/pylint-django#200]
Hi, awesome package but it still shows warnings for Meta classes in Django

I've run it via sublime text AND via cmd directly and results are the same.
PS broken imports due to vagrant.
Mac OS, Sublime-Text 3.
Thx in advance for any help !

<img width="660" alt="image" src="https://user-images.githubusercontent.com/13070119/47324752-c338f480-d669-11e8-81c0-21e7079ed172.png">

And the same output via terminal.

> /usr/local/bin/pylint --load-plugins=pylint_django /Users/artem/Desktop/MuzicBox/src/muzicbox/apps/audios/serialisers.py
> ************* Module muzicbox.apps.audios.serialisers
> serialisers.py:1:0: C0111: Missing module docstring (missing-docstring)
> serialisers.py:5:0: E0401: Unable to import 'rest_framework.serializers' (import-error)
> serialisers.py:9:0: E0401: Unable to import 'mutagen.mp3' (import-error)
> serialisers.py:18:0: C0103: Constant name "std_logger" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
> serialisers.py:21:0: C0111: Missing class docstring (missing-docstring)
> serialisers.py:23:4: C0111: Missing class docstring (missing-docstring)
> serialisers.py:28:0: C0111: Missing class docstring (missing-docstring)
> serialisers.py:29:4: C0111: Missing class docstring (missing-docstring)
> serialisers.py:34:0: C0111: Missing class docstring (missing-docstring)
> serialisers.py:42:4: C0111: Missing class docstring (missing-docstring)
> serialisers.py:50:0: C0111: Missing class docstring (missing-docstring)
> serialisers.py:58:4: C0111: Missing class docstring (missing-docstring)
> serialisers.py:66:4: C0111: Missing method docstring (missing-docstring)
> serialisers.py:66:4: R0201: Method could be a function (no-self-use)
> 

**Pip freeze**

> altgraph==0.10.2
> ansible==2.6.4
> arrow==0.12.1
> asn1crypto==0.24.0
> astroid==1.6.5
> backports.functools-lru-cache==1.5
> bcrypt==3.1.4
> bdist-mpkg==0.5.0
> binaryornot==0.4.4
> bonjour-py==0.3
> certifi==2018.8.24
> cffi==1.11.5
> chardet==3.0.4
> Click==7.0
> configparser==3.5.0
> cryptography==2.3.1
> enum34==1.1.6
> future==0.16.0
> futures==3.2.0
> idna==2.7
> ipaddress==1.0.22
> isort==4.3.4
> Jinja2==2.10
> jinja2-time==0.2.0
> lazy-object-proxy==1.3.1
> macholib==1.5.1
> MarkupSafe==1.0
> matplotlib==1.3.1
> mccabe==0.6.1
> modulegraph==0.10.4
> numpy==1.8.0rc1
> paramiko==2.4.1
> poyo==0.4.2
> py2app==0.7.3
> pyasn1==0.4.4
> pycparser==2.18
> pylint==1.9.3
> PyNaCl==1.2.1
> pyobjc-core==2.5.1
> pyobjc-framework-Accounts==2.5.1
> pyobjc-framework-AddressBook==2.5.1
> pyobjc-framework-AppleScriptKit==2.5.1
> pyobjc-framework-AppleScriptObjC==2.5.1
> pyobjc-framework-Automator==2.5.1
> pyobjc-framework-CFNetwork==2.5.1
> pyobjc-framework-Cocoa==2.5.1
> pyobjc-framework-Collaboration==2.5.1
> pyobjc-framework-CoreData==2.5.1
> pyobjc-framework-CoreLocation==2.5.1
> pyobjc-framework-CoreText==2.5.1
> pyobjc-framework-DictionaryServices==2.5.1
> pyobjc-framework-EventKit==2.5.1
> pyobjc-framework-ExceptionHandling==2.5.1
> pyobjc-framework-FSEvents==2.5.1
> pyobjc-framework-InputMethodKit==2.5.1
> pyobjc-framework-InstallerPlugins==2.5.1
> pyobjc-framework-InstantMessage==2.5.1
> pyobjc-framework-LatentSemanticMapping==2.5.1
> pyobjc-framework-LaunchServices==2.5.1
> pyobjc-framework-Message==2.5.1
> pyobjc-framework-OpenDirectory==2.5.1
> pyobjc-framework-PreferencePanes==2.5.1
> pyobjc-framework-PubSub==2.5.1
> pyobjc-framework-QTKit==2.5.1
> pyobjc-framework-Quartz==2.5.1
> pyobjc-framework-ScreenSaver==2.5.1
> pyobjc-framework-ScriptingBridge==2.5.1
> pyobjc-framework-SearchKit==2.5.1
> pyobjc-framework-ServiceManagement==2.5.1
> pyobjc-framework-Social==2.5.1
> pyobjc-framework-SyncServices==2.5.1
> pyobjc-framework-SystemConfiguration==2.5.1
> pyobjc-framework-WebKit==2.5.1
> pyOpenSSL==0.13.1
> pyparsing==2.0.1
> python-dateutil==1.5
> pytz==2013.7
> PyYAML==3.13
> requests==2.19.1
> scipy==0.13.0b1
> singledispatch==3.4.0.3
> six==1.4.1
> urllib3==1.23
> virtualenv==16.0.0
> whichcraft==0.4.1
> wrapt==1.10.11
> xattr==0.6.4
> zope.interface==4.1.1
>

**Comment by carlio** [comment]
@ArtemBernatskyy can you try this with `pylint-django==2.0.4` and `pylint==2.2.0` ? I think there are two fixes in these releases that might fix this as a coincidence.

**Comment by ArtemBernatskyy** [comment]
Sure @carlio , but somehow it still behaves the same way (

**Comment by carlio** [comment]
It seems that the only thing is that it warns about a missing docstring (line 21, the rest are outside of the Meta class) so you could fix this by adding a docstring, adding a `# pylint: disable=missing-docstring` on your metaclass, or disabling it globally.

If that is the only error, ultimately it is still a warning that is valid! pylint-django was just trying to stop spurious things such as 'does not extend from `(object)`' that are django specific.

**Comment by ArtemBernatskyy** [comment]
Ok, thx for help @carlio

**Comment by carlio** [comment]
No worries @ArtemBernatskyy 👍
