### ISSUE TITLE
Tidy up compat

### ISSUE THREAD

**Issue by carlio** [PyCQA/pylint-django#205]
As part of #201 #203 fixes in #204 I just added the old `compat.py` back in.

I only used the `YES`==`Uninferable` for now but I did not revert any other changes as they clearly work.

Since this library has open ended ranges, I think it is useful to have a single place to put the various hacks/workarounds that come from supporting `pylint==2.1`->`pylint==latest` as is the current case.

Ideally all those hacks should go into the same place for easy of cleaning. The previous code (and the code that is now there) were not really cleaned out enough and there's lots of unecessary bits.

This issues is to:

1) clear out the previous legacy things which are no longer useful due to not supporting ancient pylint versions, eg the method mis-spellings
2) figure out how to add new fixes for newer pylint/astroid etc releases.

The fact is that as pylint-django is used in lots of build processes in lots of configurations, any time there is a bug due to bad code in pylint-django or upstream changes, lots of people will waste time figuring out why their builds now error and we will get bug reports. It's in the best interests of everyone to have a good strategy to cope with this - trust me from 5 years of this :-)

@atodorov That is mostly for you to read

**Comment by atodorov** [comment]
See #206 (I didn't see this notification after I submitted the PR)

**Comment by atodorov** [comment]
no objections on my side
