### ISSUE TITLE
Does not handle ForeignKey model fields

### ISSUE THREAD

**Issue by carlio** [PyCQA/pylint-django#21]
A `ForeignKey` field on a model results in logs of "instance of ForeignKey has no member x" warnings as pylint does not know that Django swaps out the attribute.

**Comment by ysfjwd** [comment]
This fixes only for the first time an attribute is called, not if you have multiple methods e.g.

```python
  @property
  def name(self):
    return self.item.name

  @property
  def category(self):
    return self.item.category.name

  @property
  def family(self):
    return self.item.category.family

  @property
  def outlet_category(self):
    return OutletCategory.objects.get(category=self.item.category, outlet=self.outlet).id
```

the category, family and outlet_category will raise the error.

**Comment by atodorov** [comment]
@ysfjwd please open a new issue for your problem and post the entire model class which reproduces the issue and all error logs that you have. What you've given is not enough to reproduce since I have no idea what `self.item` is!

**Comment by ysfjwd** [comment]
@atodorov created a new issue #142
