### ISSUE TITLE
Do not use versions 2.0.3 and 2.0.4, use 2.0.5

### ISSUE THREAD

**Issue by atodorov** [PyCQA/pylint-django#213]
Use the latest 2.0.5

@carlio - when you've built 2.0.3 you've tagged it as 2.0.4 in git and for some reason 2.0.4 on PyPI. Maybe you had a built which you pushed unintentionally. 

Then I rewrote the 2.0.4 tag on GitHub this morning and also went back to create a 2.0.3 tag to keep a reference to the previous version. Then I uploaded to PyPI which happily accepted the wheel package for 2.0.4 and then failed because a tar.gz tagged 2.0.4 already existed.

I've pushed a 2.0.5 version in an attempt to clean up this mess and updated changelog. You can close this issue when you read it.

**Comment by carlio** [comment]
@atodorov Yeah this was my mistake - I released 2.0.3 to pypi but had forgotten to pull latest master so 2.0.3 on PyPi was actually just the same as 2.0.2, so I had to delete that release completely and skip it.

I mentioned it on [this comment here] but forgot to document it properly elsewhere. Basically it was a mis-release that I had to clean up.
