### ISSUE TITLE
AstroidImportError when ForeignKey points to app not in root module

### ISSUE THREAD

**Issue by federicobond** [PyCQA/pylint-django#233]
I have a project structure where Django apps live in an `apps/` directory. This makes the import path for a model at `apps.myapp.models.MyModel`.

When pylint_django processes the ForeignKey, it tries to load `myapp.models`, resulting in an `astroid.exceptions.AstroidImportError`. The only way around it as I see is to actually read the contents of `INSTALLED_APPS` settings variable.

**Comment by err204** [comment]
+

**Comment by atodorov** [comment]
I'm seeing the same issue but there's no reliable way to get this information from Django's INSTALLED_APPS.  Applications can define an `AppConfig` class and have a name different from their actual Python module. On top of this Django requires the format for foreign keys to be "app_name.ModelName" and you can't have dots in the app_name while I have a project where AppConfig uses dots in the app_name.


The solution is to modify the PYTHONPATH variable and instruct pylint where to find these additional modules:

```
$ PYTHONPATH=~/Kiwi/tcms/ pylint --load-plugins pylint_django tcms/testplans/models.py
```

My ForeignKey relations look like `ForeignKey('management.Tag')` while the module is `tcms.management.models`
