### ISSUE TITLE
Unable to install latest version of pylint-django

### ISSUE THREAD

**Issue by IntelligentFunction** [PyCQA/pylint-django#253]
**WARNING:**  Please do not report issues about missing Django, see
[README](https://github.com/PyCQA/pylint-django#installation)!

**TODO:** make sure to post the output of `pip freeze`
astroid==1.6.6
backports.functools-lru-cache==1.6.1
configparser==4.0.2
enum34==1.1.6
futures==3.3.0
isort==4.3.21
lazy-object-proxy==1.4.3
logilab-astng==0.24.3
logilab-common==1.4.3
mccabe==0.6.1
singledispatch==3.4.0.3
six==1.13.0
wrapt==1.11.2

**NOTES:**  make sure you have the latest version of 3rd party packages
like `rest_framework`, `factory`, `model_utils`, etc. before reporting
issues!

Trying to install pylint-django but I get the following error:
Collecting pylint-django
  Using cached https://files.pythonhosted.org/packages/05/01/1e7241e247d544aed790391b3a3a4f0e2cd93b7604e5a50ef3323ce5a812/pylint-django-2.0.12.tar.gz
Collecting pylint-plugin-utils>=0.5 (from pylint-django)
  Using cached https://files.pythonhosted.org/packages/5c/94/2f1a7a2468c42be1a57520e0a85953c5cef5f0672c5081c5e66f8d4a7d86/pylint-plugin-utils-0.6.tar.gz
Collecting pylint>=2.0 (from pylint-django)
  Could not find a version that satisfies the requirement pylint>=2.0 (from pylint-django) (from versions: 0.15.2, 0.16.0, 0.18.0, 0.18.1, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.27.0, 0.28.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5)
No matching distribution found for pylint>=2.0 (from pylint-django)

**Comment by atodorov** [comment]
This looks like Python2 or unsupported Python3 or a transient network error.

Clearly you can find the 2.0 and later versions of pylint on PyPI.

Since v2.0 we don't support Python 2, nor does pylint itself, see CHANGELOG.
