### ISSUE TITLE
ForeignKey("auth.Group") leads to AstroidImportError

### ISSUE THREAD

**Issue by michael-k** [PyCQA/pylint-django#264]
With the latest releases of [astroid](https://github.com/PyCQA/astroid), pylint, and pylint-django I noticed that using `group = models.ForeignKey("auth.Group", on_delete=models.CASCADE)` in a model leads to an exception when running pylint.

The problem is `"auth.Group"`.  transforms/foreignkey.py [rewrites](https://github.com/PyCQA/pylint-django/blob/4f37bf33543b5d99cf11306f14251430beb60548/pylint_django/transforms/foreignkey.py#L93) the `auth` to `auth.models` which leads to `astroid.exceptions.AstroidImportError: Failed to import module auth.models with error: No module named auth.models.`.

A workaround is to add `from django.contrib.auth.models import Group` and change the field to `group = models.ForeignKey(Group, on_delete=models.CASCADE)`.

Here's a minimal example: https://github.com/michael-k/pylinttest
Clone the repo and run the following commands to reproduce the exeption:

```sh
docker build --pull --no-cache --tag="pylinttest:latest" .
docker run --rm --volume=$(pwd):/code pylinttest:latest pylint /code/pylinttest/main/models.py
```

> make sure to post the output of `pip freeze`

See https://github.com/michael-k/pylinttest/blob/master/requirements.txt (generated with pip-compile)

**Comment by tklarryonline** [comment]
This issue affects one of our repo since we are using `'auth.User'`. The workaround is okay but it leads to lots of code changes. Will this issue be addressed in the next upgrades? Let me know if it is.

**Comment by atodorov** [comment]
https://github.com/PyCQA/pylint-django#known-issues
