### ISSUE TITLE
pinned Faker==5.0.1 causing packages installation conflicts

### ISSUE THREAD

**Issue by robinchow** [PyCQA/pylint-django#302]
Due to this update (https://github.com/PyCQA/pylint-django/commit/9b50595800fb9f5b2063db2b9c391024ab39e4c6) and the pin being so restrictive, we are encountering the problem of "incompatible versions in resolved dependencies" when installing packages in our environment (we use `Faker==4.18.0`)

If you're trying to avoid Faker version 5.0.2, maybe instead use the requirement `Faker<5.0.2` ?

**Comment by atodorov** [comment]
@robinchow makes sense. Do you mind sending a PR ?

**Comment by carlio** [comment]
This was fixed as part of #304 and #305, it was just released as version 2.4.2
