### ISSUE TITLE
Why is Faker a required dependency?

### ISSUE THREAD

**Issue by OutOfFocus4** [PyCQA/pylint-django#304]
I installed the most recent version of `pylint-django`, and it installed the `faker` package. It doesn’t look like `pylint-django` uses `faker` anywhere, so why was this dependency added?

**Comment by carlio** [comment]
It's a dependency of astroid which is a dependency of pylint which is a dependency of pylint-django, and there was some kind of conflict - see https://github.com/PyCQA/pylint-django/pull/300

**Comment by atodorov** [comment]
@carlio thinking about it though @OutOfFocus4 got some point. We should have probably pinned Faker only in CI and not force it onto users.

@jpulec does installing newer Faker versions when running a released pylint-django cause the same crash we saw it the tests or no? That is is there any option to pin the version only in our own CI or not ?

**Comment by OutOfFocus4** [comment]
I have `astroid` 2.4.2 installed on my local machine, and running `pip show astroid` indicates that its dependencies are `six`, `lazy-object-proxy`, `typed-ast`, and `wrapt`.

**Comment by carlio** [comment]
Using `pipdeptree`, Faker comes from the factoryboy dependency, which we only use for tests, therefore @atodorov I think we could just move the Faker dependency into the `extras_require[for_tests]` section.

**Comment by jpulec** [comment]
@atodorov It's only a problem for tests. As @carlio has recommended, it should instead get moved to `extras_require[for_tests]`.

**Comment by carlio** [comment]
@atodorov @jpulec I made a PR (#305 ) to sort this out, I'll leave it open to give you a chance to review but as it's quite small, I'll release it tomorrow as a minor version if there are no objections.

**Comment by atodorov** [comment]
Fixed in v2.4.2, pushed to PyPI just now.

**Comment by carlio** [comment]
@atodorov oops, thanks for releasing I had forgotten to do it :-)
