### ISSUE TITLE
Feature - Add options of DJANGO_SETTING_MODULE to be added to .pylintrc 

### ISSUE THREAD

**Issue by luke-goddard** [PyCQA/pylint-django#312]
Would it be possible to add DJANGO_SETTING_MODULE to the pylintrc file?

**Comment by pzanitti** [comment]
It's supported, just drop `django-settings-module=yourproject.settings` below `load-plugins=pylint_django`.

**Comment by pzanitti** [comment]
Keep in mind editor linting will silently fail if you're using `django-configurations` and pylint-django>=2.4.0 as per #306 #307 etc.

If you are, install and stay in 2.3.0.

**Comment by luke-goddard** [comment]
Perfect thank you that worked :) I'm quite new to configuring pylint it's not obvious to newcomers that this is possible.

**Comment by atodorov** [comment]
> Perfect thank you that worked :) I'm quite new to configuring pylint it's not obvious to newcomers that this is possible.

How about https://github.com/PyCQA/pylint-django#usage ? Wasn't that obvious enough ?

**Comment by carlio** [comment]
@atodorov The issue was about adding to `.pylintrc` which isn't mentioned in the README, might be worth adding it.
