### ISSUE TITLE
pylint 2.8.3 issue

### ISSUE THREAD

**Issue by ppolu-softserveinc** [PyCQA/pylint-django#328]
`('2', '8', '3')
Traceback (most recent call last):
  File "/home/ppolu/web/**/venv/lib/python3.8/site-packages/pylint_django/compat.py", line 29, in <module>
    LOAD_CONFIGURATION_SUPPORTED = pylint.__pkginfo__.numversion >= (2, 3)
TypeError: '>=' not supported between instances of 'str' and 'int'
`
The guy who doesn't map a tuple to int and hope everything will be okay - thanks for 10 minutes of my wasted time.

**Comment by bghimire2** [comment]
I found this same bug too.

**Comment by sparrowt** [comment]
AFAICS this was fixed in https://github.com/pylint-dev/pylint-django/pull/324/files i.e. in pylint-django>=2.4.4
