### ISSUE TITLE
Astroid DeprecationWarning

### ISSUE THREAD

**Issue by GergelyKalmar** [PyCQA/pylint-django#339]
I'm getting the following DeprecationWarning when using pylint-django:

```
File "/home/gregory/.pyorbs/pytest-logikal/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 26, in <module>
    warnings.warn(
DeprecationWarning: The 'astroid.scoped_nodes' module is deprecated and will be replaced by 'astroid.nodes' in astroid 3.0.0
```
The warning seems to be triggered by this line: https://github.com/PyCQA/pylint-django/blob/master/pylint_django/augmentations/__init__.py#L9, but I can imagine that there might be more places that trigger the warning. Pinning astroid to version `<2.8.1` makes the warning disappear, so it was most likely introduced in that version.

**Comment by carlio** [comment]
This is fixed now in pylint-django 2.5.0 (just released today)
