### ISSUE TITLE
ForeignKey transform doesn't work when the class is specified by a string

### ISSUE THREAD

**Issue by chris-martin** [PyCQA/pylint-django#35]
Pylint-django works as advertised on a field declared like this:

``` py
field = ForeignKey(TheModel)
```

But not on this equivalent field:

``` py
field = ForeignKey('appname.TheModel')
```

**Comment by yosemitebandit** [comment]
+1 -- would be interested in learning how to avoid this problem.

**Comment by carlio** [comment]
I'm going to be honest, I have no idea without reimplementing or abusing the Django model discovery mechanism. As it's mostly meta-class magic, I *hope* that simply importing all `models.py` files would be enough to get access to the registry of models but this would involve executing the code being inspected, which could be a security issue (`pylint` deliberately disables loading C-extensions for this reason)

**Comment by chris-martin** [comment]
I think a little static-analysis reimplemention of Django model discovery could go a long way. My initial thoughts:

* Split on the last `.` to parse, e.g. `a.b.C` -> `{'app': 'a.b', 'class': 'C'}`
* Look for a class named `C` that either:
  * is in the module `a.b.models`, or
  * looks like this:

    ```
    class C:
        class Meta:
            app_label = 'a.b'
    ```

Of course it's easy to write code that breaks this, but I doubt there's much real code in the wild that does.

**Comment by NotSqrt** [comment]
I went another way:
I upgraded the ``infer_key_classes`` function with:

```python
def infer_key_classes(node, context=None):
    for arg in node.args:
        # typically the class of the foreign key will
        # be the first argument, so we'll go from left to right
        if isinstance(arg, (nodes.Name, nodes.Getattr)):
             # as before
        elif isinstance(arg, nodes.Const):
            try:
                model_name = arg.value.split('.')[-1]  # can be 'Model' or 'app.Model'
            except AttributeError:
                break

            for module in MANAGER.astroid_cache.values():
                if model_name in module.locals:
                    class_defs = [
                        module_node for module_node in module.lookup(model_name)[1]
                        if isinstance(module_node, nodes.ClassDef)
                        and node_is_subclass(module_node, 'django.db.models.base.Model')
                    ]
                    if class_defs:
                        return iter([instantiate_class(class_defs[0])()])

        # as before
```

which basically looks up all classes found in all modules to find a subclass of ``Model`` that has the expected name.

**Comment by atodorov** [comment]
Looks like this is working with the latest version of pylint_django. I've added a test and will send a PR very soon. I will close this issue in a few days if I don't hear from it with a reproducer that still shows the problem.
