### ISSUE TITLE
Fix missing `scope_type` positional argument for ScopeConsumer

### ISSUE THREAD

**Issue by carlio** [PyCQA/pylint-django#358]
You may see stack-traces containing things like:

```
    consumer._atomic = ScopeConsumer(new_things, consumer.consumed, consumer.scope_type)  # pylint: disable=W0212
TypeError: <lambda>() missing 1 required positional argument: 'scope_type'
```

To fix this, pylint-django needs to add backwards/forwards compatibility for ScopeConsumer

See the original issue here - https://github.com/PyCQA/pylint/issues/5970#issuecomment-1078778393

Pylint 2.13 changed the shape of the ScopeConsumer tuple so pylint-django needs to handle that.

**Comment by DanielNoord** [comment]
> Just an update on this ticket : I have a fix in the master branch, however another change in pylint 2.13 requires some changes to how pylint-django runs tests.

We should probably package this 😄 

Hopefully I remember to do this.

**Comment by carlio** [comment]
Ok, 2.5.3 is on PyPI now with the fix in despite `tox` doing its best to make me angry.

**Comment by Pierre-Sassoulas** [comment]
@DanielNoord would you like me to open an issue ? By packaging do you mean we package the default pylintrc file in ``pylint.testutil`` ? We could also add a default value created at runtime.

**Comment by carlio** [comment]
The specific problem I ran in to was from here - https://github.com/PyCQA/pylint/blob/main/pylint/testutils/lint_module_test.py#L48 - the `testing_pylintrc` does not exist when using pylint is a dependency.

I'd say that it should be packaged if "LintModuleTest" is considered a public API, but if not then it's an internal thing again and external plugins should handle it themselves; however with some kind of way to do it without monkeypatching the module as I did.

**Comment by Pierre-Sassoulas** [comment]
Yeah, I got the idea for the runtime generation from the content of your commit just above that referenced this issue @carlio 😄 (https://github.com/PyCQA/pylint-django/commit/a731230c369aa2f6640dc80dfa5cd4eea140a3d5)

**Comment by DanielNoord** [comment]
I think it is required as we expose our functional test framework specifically for your use case: allow testing pylint plugins like we test the main checker.

I'm no setup tools expert and don't have much time this weekend, so if somebody finds the time to open a PR please do so. 
I think this warrant a new patch release because this will break functional tests for all plugins that use is and update to 2.13.
