### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by davebulaval** [PyCQA/pylint-django#368]
Is it possible to link to successful projects using PyLint-Django? I've tried setting the Django setup, but I just never work. I've tried reading the Django doc but still have no idea how to properly organize the repo to access the settings.

Thanks.

**Comment by atodorov** [comment]
https://github.com/kiwitcms/Kiwi/blob/master/Makefile#L50

**Comment by davebulaval** [comment]
I've got the hang of it, but it seems like GitHub actions are more picky than local. Tks for the help. I would recommend adding it to the README.
