### ISSUE TITLE
Help configuring pylint_django with django settings module

### ISSUE THREAD

**Issue by dwaynelaforce** [PyCQA/pylint-django#377]
Hello!  I did my best to follow the documentation but I am getting a ModuleNotFoundError when running the command:

`pylint --load-plugins pylint_django --django-settings-module project.settings .`

I wasn't sure what is meant in the readme by `<path_to_your_sources>` so I just put my current working directory which is the root repo directory for my project.  I've tried several variations of this, each time resulting in the ModuleNotFoundError.  When `<path_to_your_sources>` is ommitted, I am greeted with a lot of pylint help info including --django-settings-module at the bottom.

My project is organized as follows:

/repo
--/venv (pylint and django-pylint are here)
--/app
--/project (settings.py is here)

Any help or update to the readme would be appreciated!

**Comment by KJSanchez** [comment]
I got the same error, however I was able to resolve it with an earlier version of pylint.

```bash
pip install pylint==2.14
```

**Comment by dwaynelaforce** [comment]
Thank you @KJSanchez that worked for me!
