### ISSUE TITLE
Ignore old-style-class for django-tables2 table Meta

### ISSUE THREAD

**Issue by federicobond** [PyCQA/pylint-django#56]
I tried making the change myself in the `is_model_meta_subclass` parents whitelist but it didn't work.

The `node_is_subclass` check fails because `inferred(base_cls)()` returns `[YES]` instead of (presumably) a `ClassDef` node, but I couldn't track it down much further. It may have to do with the way that the Meta class is configured in `django-tables2`. See [here](https://github.com/bradleyayers/django-tables2/blob/master/django_tables2/tables.py).

**Comment by atodorov** [comment]
I've added tests for this in https://github.com/PyCQA/pylint-django/pull/125 but it looks like it's not a problem anymore. Closing.
